config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :images
  resources :products
  root 'categories#index'

end

app/models/category.rb
#
# @author  Bala Subrahmanyam
#
# Category Model
class Category < ActiveRecord::Base
  belongs_to :parent, class_name: 'Category'

  has_many :products
  has_many :images, as: :parent, dependent: :destroy
  has_many :sub_categories, class_name: 'Category', foreign_key: 'parent_id'

  accepts_nested_attributes_for :products, reject_if: :all_blank, allow_destroy: true

  validates_presence_of :name
end

app/models/image.rb
#
# @author  Bala Subrahmanyam
#
# Image Model
class Image < ActiveRecord::Base
  belongs_to :parent, polymorphic: true

  has_attached_file :image,
                    styles: { small: '150x150>' },
                    url: '/uploads/images/:id/:style/:basename.:extension',
                    path: ':rails_root/public/uploads/images/:id/:style/:basename.:extension'

  validates_presence_of :parent
  validates_attachment_presence :image
  validates_attachment_content_type :image, content_type: ['image/jpeg', 'image/png']
end

app/models/product.rb
#
# @author  Bala Subrahmanyam
#
# Product Model
class Product < ActiveRecord::Base
  belongs_to :category
  has_many :images, as: :parent

  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
#
# @author  Bala Subrahmanyam
#
# Category Controller
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @categories }
    end
  end

  def show
    @images = @category.images
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @category }
    end
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    respond_to do |format|
      if @category.save
        params[:images].each do |image|
          @category.images.create(image: image)
        end if params[:images].present?
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        params[:images].each do |image|
          @category.images.create(image: image)
        end if params[:images]
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render json: @category, status: :created }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(
      :name,
      :parent_id,
      products_attributes: [:id, :name])
  end
end

app/controllers/images_controller.rb
# Images Controller
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  def index
    @images = Image.all
  end

  def show
  end

  def new
    @image = Image.new
  end

  def edit
  end

  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_image
    @image = Image.find(params[:id])
  end

  def image_params
    params.require(:image).permit(:name, :category_id)
  end
end

app/controllers/products_controller.rb
# Products Controller
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_form.html.slim
= form_for @category, html: { class: "form form-horizontal category", multipart: true } do |f|
  - if @category.errors.any?
    #error_expl.panel.panel-danger
      .panel-heading
        h3.panel-title
          = pluralize(@category.errors.count, "error")
          |  prohibited this category from being saved:
      .panel-body
        ul
          - @category.errors.full_messages.each do |msg|
            li
              = msg
  .form-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'form-control'
    = error_span(@category[:name])
  .form-group
    = f.label :parent_id, :class => 'control-label'
    .controls
    = f.select :parent_id, Category.all.collect { |c| [c.name, c.id] }, { include_blank: true }, {:class => 'form-control'}

  .form-group
    = f.label :products, :class => 'control-label'
    .controls
      = f.fields_for :products do |product|
        - render 'product_fields', f: product
      .links
        = link_to_add_association 'add product', f, :products, :class => 'btn btn-default btn-xs'
  .form-group
    = f.label :images, :class => 'control-label'
    .controls
      = file_field_tag 'images[]', type: :file, multiple: true
    = error_span(@category[:parent_id])
  = f.submit nil, :class => 'btn btn-primary'
  '
  = link_to t('.cancel', :default => t("helpers.links.cancel")), categories_path, :class => 'btn'

app/views/categories/_product_fields.html.slim
.nested-fields
  .field
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'form-control'
    = link_to_remove_association "remove product", f, :class => 'btn btn-xs btn-danger'

app/views/categories/edit.html.slim
- model_class = Category
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/categories/index.html.slim
- model_class = Category
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
table class="table table-striped"
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:name)
      th= model_class.human_attribute_name(:parent_id)
      th= model_class.human_attribute_name(:created_at)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @categories.each do |category|
      tr
        td= link_to category.id, category_path(category)
        td= category.name
        td= category.parent_id
        td=l category.created_at
        td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_category_path(category), :class => 'btn btn-default btn-xs'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), category_path(category), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_category_path, :class => 'btn btn-primary'

app/views/categories/new.html.slim
- model_class = Category
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/categories/show.html.slim
- model_class = Category
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.titleize

p
  strong= model_class.human_attribute_name(:name) + ':'
  br
  = @category.name
p
  strong= model_class.human_attribute_name(:parent_id) + ':'
  br
  - if @category.parent.present?
    strong= @category.class.human_attribute_name(:id) + ':'
    | &nbsp;
    = link_to(@category.parent.id, category_path(@category.parent))
    br
    strong= @category.parent.class.human_attribute_name(:name) + ':'
    | &nbsp;
    = @category.parent.name
    hr

- unless @category.sub_categories.empty?
  p
    strong= model_class.human_attribute_name(:sub_categories) + ':'
    ul
      - @category.sub_categories.each do |sub_category|
        li
          strong= sub_category.class.human_attribute_name(:id) + ':'
          | &nbsp;
          = link_to(sub_category.id, category_path(sub_category))
          br
          strong= sub_category.class.human_attribute_name(:name) + ':'
          | &nbsp;
          = sub_category.name
          hr

- unless @category.products.empty?
  p
    strong= model_class.human_attribute_name(:products) + ':'
    ul
      - @category.products.each do |product|
        li
          strong= product.class.human_attribute_name(:name) + ':'
          | &nbsp;
          = product.name
          | &nbsp;
          = link_to t('.destroy', :default => t("helpers.links.destroy")), product_path(product), :method => 'delete', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'
- unless @images.empty?
  p
    strong= model_class.human_attribute_name(:images) + ':'
    ul
      - @images.each do |image|
        li
          = image_tag image.image.url,  :style => "width: 60px; height: 60px;"
          | &nbsp;
          = link_to t('.destroy', :default => t("helpers.links.destroy")), image_path(image), :method => 'delete', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'
= link_to t('.back', :default => t("helpers.links.back")), categories_path, :class => 'btn btn-default'
'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_category_path(@category), :class => 'btn btn-default'
'
= link_to t('.destroy', :default => t("helpers.links.destroy")), category_path(@category), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/images/_form.html.slim
= form_for @image, html: { class: "form form-horizontal image" } do |f|
  .form-group
    = f.label :parent_id, :class => 'control-label'
    .controls
      = f.text_field :parent_id, :class => 'form-control'
    = error_span(@image[:parent_id])
  .form-group
    = f.label :parent_type, :class => 'control-label'
    .controls
      = f.text_field :parent_type, :class => 'form-control'
    = error_span(@image[:parent_type])
  .form-group
    = f.label :image_file_name, :class => 'control-label'
    .controls
      = f.text_field :image_file_name, :class => 'form-control'
    = error_span(@image[:image_file_name])
  .form-group
    = f.label :image_content_type, :class => 'control-label'
    .controls
      = f.text_field :image_content_type, :class => 'form-control'
    = error_span(@image[:image_content_type])
  .form-group
    = f.label :image_file_size, :class => 'control-label'
    .controls
      = f.text_field :image_file_size, :class => 'form-control'
    = error_span(@image[:image_file_size])
  .form-group
    = f.label :image_updated_at, :class => 'control-label'
    .controls
      = f.text_field :image_updated_at, :class => 'form-control'
    = error_span(@image[:image_updated_at])
  = f.submit nil, :class => 'btn btn-primary'
  '
  = link_to t('.cancel', :default => t("helpers.links.cancel")), images_path, :class => 'btn'

app/views/images/edit.html.slim
- model_class = Image
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/images/index.html.slim
- model_class = Image
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
table class="table table-striped"
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:parent_id)
      th= model_class.human_attribute_name(:parent_type)
      th= model_class.human_attribute_name(:image_file_name)
      th= model_class.human_attribute_name(:image_content_type)
      th= model_class.human_attribute_name(:image_file_size)
      th= model_class.human_attribute_name(:image_updated_at)
      th= model_class.human_attribute_name(:created_at)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @images.each do |image|
      tr
        td= link_to image.id, image_path(image)
        td= image.parent_id
        td= image.parent_type
        td= image.image_file_name
        td= image.image_content_type
        td= image.image_file_size
        td= image.image_updated_at
        td=l image.created_at
        td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_image_path(image), :class => 'btn btn-default btn-xs'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), image_path(image), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_image_path, :class => 'btn btn-primary'

app/views/images/new.html.slim
- model_class = Image
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/images/show.html.slim
- model_class = Image
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.titleize

p
  strong= model_class.human_attribute_name(:parent_id) + ':'
  br
  = @image.parent_id
p
  strong= model_class.human_attribute_name(:parent_type) + ':'
  br
  = @image.parent_type
p
  strong= model_class.human_attribute_name(:image_file_name) + ':'
  br
  = @image.image_file_name
p
  strong= model_class.human_attribute_name(:image_content_type) + ':'
  br
  = @image.image_content_type
p
  strong= model_class.human_attribute_name(:image_file_size) + ':'
  br
  = @image.image_file_size
p
  strong= model_class.human_attribute_name(:image_updated_at) + ':'
  br
  = @image.image_updated_at

= link_to t('.back', :default => t("helpers.links.back")), images_path, :class => 'btn btn-default'
'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_image_path(@image), :class => 'btn btn-default'
'
= link_to t('.destroy', :default => t("helpers.links.destroy")), image_path(@image), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/layouts/application.html.slim
doctype html
html[lang="en"]
  head
    meta[charset="utf-8"]
    meta[http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"]
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : "Products"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
  body
    .navbar.navbar-default.navbar-static-top
      .container
        button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"]
          span.icon-bar
          span.icon-bar
          span.icon-bar
        = link_to "Categories", root_path, { :class => 'navbar-brand'}
    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield

app/views/products/_form.html.slim
= form_for @product, html: { class: "form form-horizontal product" } do |f|
  .form-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'form-control'
    = error_span(@product[:name])
  .form-group
    = f.label :category_id, :class => 'control-label'
    .controls
      = f.text_field :category_id, :class => 'form-control'
    = error_span(@product[:category_id])
  = f.submit nil, :class => 'btn btn-primary'
  '
  = link_to t('.cancel', :default => t("helpers.links.cancel")), products_path, :class => 'btn'

app/views/products/edit.html.slim
- model_class = Product
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/products/index.html.slim
- model_class = Product
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
table class="table table-striped"
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:name)
      th= model_class.human_attribute_name(:category_id)
      th= model_class.human_attribute_name(:created_at)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @products.each do |product|
      tr
        td= link_to product.id, product_path(product)
        td= product.name
        td= product.category_id
        td=l product.created_at
        td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_product_path(product), :class => 'btn btn-default btn-xs'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), product_path(product), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_product_path, :class => 'btn btn-primary'

app/views/products/new.html.slim
- model_class = Product
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/products/show.html.slim
- model_class = Product
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.titleize

p
  strong= model_class.human_attribute_name(:name) + ':'
  br
  = @product.name
p
  strong= model_class.human_attribute_name(:category_id) + ':'
  br
  = @product.category_id

= link_to t('.back', :default => t("helpers.links.back")), products_path, :class => 'btn btn-default'
'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_product_path(@product), :class => 'btn btn-default'
'
= link_to t('.destroy', :default => t("helpers.links.destroy")), product_path(@product), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'